import type { ScenarioIntensity, ScenarioPresetId, ScenarioSpec } from './types.js';

const EXTREME = 1;
const HIGH = 0.72;
const NORMAL = 0.4;
const LOW = 0.12;

function intensity(partial: Partial<ScenarioIntensity>): ScenarioIntensity {
  return {
    aggressiveBuy: 0,
    aggressiveSell: 0,
    askDepth: NORMAL,
    bidDepth: NORMAL,
    askReplenishment: NORMAL,
    bidReplenishment: NORMAL,
    askWithdrawal: LOW,
    bidWithdrawal: LOW,
    volatility: NORMAL,
    oiChange: 0,
    funding: 0,
    longLiquidations: 0,
    shortLiquidations: 0,
    ...partial,
  };
}

const BTC = 79_100;

export const SCENARIO_PRESETS: Record<ScenarioPresetId, ScenarioSpec> = {
  STRONG_BUY_BREAKOUT: {
    id: 'STRONG_BUY_BREAKOUT',
    label: 'Strong buy breakout',
    symbol: 'BTCUSDT',
    marketType: 'perp',
    seed: 42,
    durationMs: 8_000,
    startPrice: BTC,
    tickSize: 50,
    levelStep: 50,
    intensity: intensity({
      aggressiveBuy: EXTREME,
      askDepth: LOW,
      askReplenishment: LOW,
      askWithdrawal: HIGH,
      bidDepth: HIGH,
      volatility: HIGH,
    }),
  },
  SELLER_ABSORPTION: {
    id: 'SELLER_ABSORPTION',
    label: 'Seller absorption',
    symbol: 'BTCUSDT',
    marketType: 'perp',
    seed: 7,
    durationMs: 8_000,
    startPrice: BTC,
    tickSize: 50,
    levelStep: 50,
    intensity: intensity({
      aggressiveSell: EXTREME,
      bidDepth: HIGH,
      bidReplenishment: EXTREME,
      bidWithdrawal: LOW,
      askDepth: NORMAL,
    }),
  },
  BUYER_ABSORPTION: {
    id: 'BUYER_ABSORPTION',
    label: 'Buyer absorption',
    symbol: 'BTCUSDT',
    marketType: 'perp',
    seed: 11,
    durationMs: 8_000,
    startPrice: BTC,
    tickSize: 50,
    levelStep: 50,
    intensity: intensity({
      aggressiveBuy: EXTREME,
      askDepth: HIGH,
      askReplenishment: EXTREME,
      askWithdrawal: LOW,
      bidDepth: NORMAL,
    }),
  },
  UPSIDE_LIQUIDITY_VACUUM: {
    id: 'UPSIDE_LIQUIDITY_VACUUM',
    label: 'Upside liquidity vacuum',
    symbol: 'BTCUSDT',
    marketType: 'perp',
    seed: 19,
    durationMs: 8_000,
    startPrice: BTC,
    tickSize: 50,
    levelStep: 50,
    intensity: intensity({
      aggressiveBuy: NORMAL,
      askDepth: LOW,
      askReplenishment: LOW,
      askWithdrawal: EXTREME,
      volatility: HIGH,
    }),
  },
  DOWNSIDE_LIQUIDITY_VACUUM: {
    id: 'DOWNSIDE_LIQUIDITY_VACUUM',
    label: 'Downside liquidity vacuum',
    symbol: 'BTCUSDT',
    marketType: 'perp',
    seed: 23,
    durationMs: 8_000,
    startPrice: BTC,
    tickSize: 50,
    levelStep: 50,
    intensity: intensity({
      aggressiveSell: NORMAL,
      bidDepth: LOW,
      bidReplenishment: LOW,
      bidWithdrawal: EXTREME,
      volatility: HIGH,
    }),
  },
  SHORT_SQUEEZE: {
    id: 'SHORT_SQUEEZE',
    label: 'Short squeeze',
    symbol: 'BTCUSDT',
    marketType: 'perp',
    seed: 31,
    durationMs: 10_000,
    startPrice: 79_000,
    tickSize: 50,
    levelStep: 50,
    intensity: intensity({
      aggressiveBuy: HIGH,
      askDepth: LOW,
      askReplenishment: LOW,
      askWithdrawal: HIGH,
      oiChange: -0.6,
      shortLiquidations: EXTREME,
      volatility: HIGH,
    }),
    liquidationZones: [
      { id: 's1', price: 79_300, side: 'short', quoteValue: 80_000_000 },
      { id: 's2', price: 79_500, side: 'short', quoteValue: 120_000_000 },
      { id: 's3', price: 79_800, side: 'short', quoteValue: 90_000_000 },
    ],
  },
  LONG_SQUEEZE: {
    id: 'LONG_SQUEEZE',
    label: 'Long squeeze',
    symbol: 'BTCUSDT',
    marketType: 'perp',
    seed: 37,
    durationMs: 10_000,
    startPrice: 79_000,
    tickSize: 50,
    levelStep: 50,
    intensity: intensity({
      aggressiveSell: HIGH,
      bidDepth: LOW,
      bidReplenishment: LOW,
      bidWithdrawal: HIGH,
      oiChange: -0.6,
      longLiquidations: EXTREME,
      volatility: HIGH,
    }),
    liquidationZones: [
      { id: 'l1', price: 78_700, side: 'long', quoteValue: 80_000_000 },
      { id: 'l2', price: 78_500, side: 'long', quoteValue: 120_000_000 },
      { id: 'l3', price: 78_200, side: 'long', quoteValue: 90_000_000 },
    ],
  },
  FAKE_BREAKOUT: {
    id: 'FAKE_BREAKOUT',
    label: 'Fake breakout',
    symbol: 'BTCUSDT',
    marketType: 'perp',
    seed: 41,
    durationMs: 10_000,
    startPrice: BTC,
    tickSize: 50,
    levelStep: 50,
    intensity: intensity({
      aggressiveBuy: HIGH,
      askDepth: NORMAL,
      askReplenishment: HIGH,
      askWithdrawal: LOW,
      aggressiveSell: LOW,
      bidDepth: HIGH,
    }),
  },
  BALANCED_MARKET: {
    id: 'BALANCED_MARKET',
    label: 'Balanced market',
    symbol: 'BTCUSDT',
    marketType: 'perp',
    seed: 3,
    durationMs: 8_000,
    startPrice: BTC,
    tickSize: 50,
    levelStep: 50,
    intensity: intensity({
      aggressiveBuy: NORMAL,
      aggressiveSell: NORMAL,
      askDepth: HIGH,
      bidDepth: HIGH,
      askReplenishment: NORMAL,
      bidReplenishment: NORMAL,
    }),
  },
  SPOT_LED_RALLY: {
    id: 'SPOT_LED_RALLY',
    label: 'Spot-led rally',
    symbol: 'BTCUSDT',
    marketType: 'spot',
    seed: 53,
    durationMs: 8_000,
    startPrice: BTC,
    tickSize: 50,
    levelStep: 50,
    channel: 'combined',
    intensity: intensity({
      aggressiveBuy: EXTREME,
      askDepth: LOW,
      askReplenishment: LOW,
      askWithdrawal: HIGH,
    }),
  },
  FUTURES_LED_RALLY: {
    id: 'FUTURES_LED_RALLY',
    label: 'Futures-led rally',
    symbol: 'BTCUSDT',
    marketType: 'perp',
    seed: 59,
    durationMs: 8_000,
    startPrice: BTC,
    tickSize: 50,
    levelStep: 50,
    channel: 'combined',
    intensity: intensity({
      aggressiveBuy: EXTREME,
      askDepth: LOW,
      askReplenishment: LOW,
      shortLiquidations: HIGH,
      oiChange: 0.5,
      funding: 0.0008,
    }),
  },
};

export function listPresets(): ScenarioSpec[] {
  return Object.values(SCENARIO_PRESETS);
}

export function getPreset(id: ScenarioPresetId): ScenarioSpec {
  const spec = SCENARIO_PRESETS[id];
  return {
    ...spec,
    intensity: { ...spec.intensity },
    liquidationZones: spec.liquidationZones?.map((z) => ({ ...z })),
  };
}
